insert into usuarios (email, enabled, first_name, last_name, password, user_name) values ('emitchley0@delicious.com', true, 'Emmey', 'Mitchley', '$2a$10$jfSpJFXoFkyWOiXu2wz.oOHG61TD/Lj4QFczS2amkkPsC8YX/nqNe', 'emitchley0');

insert into usuarios (email, enabled, first_name, last_name, password, user_name) values ('aleteurtre1@1688.com', true, 'Archie', 'Leteurtre', '$2a$10$7HEyda.LJxPTlK4ahRMHQuWanG1rAOBypIHqlFCClLCtJPwFFs9rC', 'aleteurtre1');

insert into roles (name) values('ROLE_USER');
insert into roles (name) values('ROLE_ADMIN');

insert into usuarios_to_roles (user_id, role_id) values(1, 1);
insert into usuarios_to_roles (user_id, role_id) values(2, 2);
insert into usuarios_to_roles (user_id, role_id) values(2, 1);

-- create table usuarios (id bigint generated by default as identity, 
-- email varchar(100), 
-- enabled boolean, 
-- first_name varchar(255), 
-- last_name varchar(255), 
-- password varchar(60), 
-- user_name varchar(20), 
-- primary key (id))

-- insert into usuarios (email, enabled, first_name, last_name, password, user_name)